project/auth_app/urls.py
from django.urls import path

from auth_app.views import RegView, UserLoginView, UserLogoutView

app_name = 'auth_app'

urlpatterns = [
    path('reg/', RegView.as_view(), name='reg'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout')
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls', namespace='main')),
    path('user/', include('user_app.urls', namespace='user')),
    path('auth/', include('auth_app.urls', namespace='auth')),

    path('admin/', admin.site.urls),
]

project/main_app/urls.py
from django.urls import path

from .views import RedirectUserProfile, RedirectIndex

app_name = 'main_app'

urlpatterns = [
    path('', RedirectIndex.as_view(), name='index'),
    path('my/', RedirectUserProfile.as_view(), name='my'),
]

project/user_app/urls.py
from django.urls import path

from .views import UserProfile, UserUpdate, UserSubscribers, UserSubscriptions

app_name = 'user_app'

urlpatterns = [
    path('<int:pk>/', UserProfile.as_view(), name='profile'),
    path('<int:pk>/subscribers/', UserSubscribers.as_view(), name='subscribers'),
    path('<int:pk>/subscriptions/', UserSubscriptions.as_view(), name='subscriptions'),
    path('update/', UserUpdate.as_view(), name='update'),
]

project/auth_app/models.py
from django.db import models

project/user_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=127)


class City(models.Model):
    name = models.CharField(max_length=127)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    age = models.PositiveSmallIntegerField()
    sex = models.BooleanField()
    username = None

    city = models.ForeignKey('user_app.City', models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField('user_app.Tag', related_name='users', blank=True)
    subscriptions = models.ManyToManyField('user_app.User', related_name='subscribers')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse('user:profile', args=(self.pk,))

project/auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from user_app.models import User


class UserRegForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'age', 'sex', 'tags', 'city')

project/auth_app/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from auth_app.forms import UserRegForm


class RegView(CreateView):
    form_class = UserRegForm
    template_name = 'auth_app/reg.html'
    success_url = reverse_lazy('auth:login')


class UserLoginView(LoginView):
    template_name = 'auth_app/login.html'
    next_page = reverse_lazy('main:my')


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('auth:login')

project/main_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import RedirectView


class RedirectIndex(RedirectView):

    def get_redirect_url(self):
        return reverse('auth:login')


class RedirectUserProfile(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self):
        return reverse('user:profile', args=[self.request.user.id])

project/user_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView

from .models import User


class UserView(LoginRequiredMixin):
    model = User
    context_object_name = 'user_object'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.request.user.subscriptions.add(self.object)
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class UserProfile(UserView, DetailView):
    pass


class UserUpdate(UpdateView, UserView):
    login_url = reverse_lazy('auth:login')
    fields = ('email', 'first_name', 'last_name', 'age', 'sex', 'city', 'tags')

    def get_object(self, queryset=None):
        return self.request.user


class UserSubscribers(UserView, DetailView):
    template_name = 'user_app/user_friends.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(object_list=self.get_object().subscribers.all(), **kwargs)


class UserSubscriptions(UserView, DetailView):
    template_name = 'user_app/user_friends.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(object_list=self.get_object().subscriptions.all(), **kwargs)

project/auth_app/templates/auth_app/login.html
{% extends 'main_app/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block style %}
    body{
    margin-top:20px;
    background:#eee;
    }
    .container {
    margin-right: auto;
    margin-left: auto;
    padding-right: 15px;
    padding-left: 15px;
    width: 100%;
    }

    @media (min-width: 576px) {
    .container {
    max-width: 540px;
    }
    }

    @media (min-width: 768px) {
    .container {
    max-width: 720px;
    }
    }

    @media (min-width: 992px) {
    .container {
    max-width: 960px;
    }
    }

    @media (min-width: 1200px) {
    .container {
    max-width: 1140px;
    }
    }



    .card-columns .card {
    margin-bottom: 0.75rem;
    }

    @media (min-width: 576px) {
    .card-columns {
    column-count: 3;
    column-gap: 1.25rem;
    }
    .card-columns .card {
    display: inline-block;
    width: 100%;
    }
    }
    .text-muted {
    color: #9faecb !important;
    }

    p {
    margin-top: 0;
    margin-bottom: 1rem;
    }
    .mb-3 {
    margin-bottom: 1rem !important;
    }

    .input-group {
    position: relative;
    display: flex;
    width: 100%;
    }
{% endblock style %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-group mb-0">
                <div class="card p-4">
                    <div class="card-body">
                        <h1>Login</h1>
                        <p class="text-muted">Sign In to your account</p>
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary btn-block mb-4">Login</button>
                        </form>
                    </div>
                </div>
                <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
                    <div class="card-body text-center">
                        <div>
                            <h2>Sign up</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua.</p>
                            <a href="{% url 'auth:reg' %}" class="btn btn-primary active mt-3">Register Now!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/auth_app/templates/auth_app/reg.html
{% extends 'main_app/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Регистрация{% endblock %}

{% block style %}
    body{
    margin-top:20px;
    background-color: #f2f3f8;
    }
    .card {
    margin-bottom: 1.5rem;
    box-shadow: 0 1px 15px 1px rgba(52,40,104,.08);
    }

    .card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid #e5e9f2;
    border-radius: .2rem;
    }
{% endblock style %}

{% block content %}
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">Get started</h1>
                        <p class="lead">
                            Start creating the best possible user experience for you customers.
                        </p>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="m-sm-4">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-primary btn-block mb-4">Зарегистрироваться
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/main_app/templates/main_app/base.html
<html lang="ru">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<title>{% block title %}{% endblock %}</title>
<style>{% block style %}{% endblock %}</style>
</head>
<body>
<div class="container">{% block content %}{% endblock %}</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
</body>
</html>

project/main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}

{% block title %}Index page{% endblock title %}

project/user_app/templates/user_app/user_detail.html
{% extends 'user_app/user_base.html' %}

project/user_app/templates/user_app/user_form.html
{% extends 'user_app/user_base.html' %}
{% load crispy_forms_tags %}

{% block user_content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary btn-block mb-4">Изменить</button>
    </form>
{% endblock %}

project/user_app/templates/user_app/user_friends.html
{% extends 'user_app/user_base.html' %}

{% block user_content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="people-nearby">
                    {% for object in object_list %}
                        <div class="nearby-user">
                            <div class="row">
                                <div class="col-md-4 col-sm-3">
                                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="user"
                                         class="profile-photo-lg">
                                </div>
                                <div class="col-md-8 col-sm-7">
                                    <h5><a href="{% url 'user:profile' object.pk %}"
                                           class="profile-link">{{ object.get_full_name }}</a></h5>
                                    <p>{{ object.email }}</p>
                                    <p class="text-muted">{{ object.city.name }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}